language: node_js
node_js:
- 0.10
before_script:
- npm install -g grunt-cli
env:
  global:
  - secure: a5mS9VWkIj4Odw1HP17anOmxe8Wm7CsLMH5w+JW7KQ3MWHpstdJdIlAr84cTsZw+LCm+gjwpU3XcIzvYNgn6me+3Wzlokjz2+xQwEY4dEbyEmhEIZE6H3y1CvBGrMZca8mmIqR3Y57KMV6HUPnNgvRiaVIihUGSjx22qA+Sjeyo=
  - secure: I+iSK4RgZHNYNtqAqNf1c9rsb6WhlrcQi1PNXAYVzUoQvfESmQU5qeSdeX1RaI13olkDs9tnHUixHIT5rYG7FF4XlCDaqLe3PJvT+0Tkw1PWK7XpLA29jYrf8XIGqb1p9W63v5VkaZT3QZ6CwLSGusjN0CcJGijbPU/bJQFV8M8=
